
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20210518.0.0"
  
  config.vm.provision "shell", inline: "curl -fsSL https://get.docker.com -o get-docker.sh"
  config.vm.provision "shell", inline: "sh get-docker.sh"
  config.vm.provision "shell", inline: "usermod -aG docker vagrant"

  config.vm.provider "virtualbox" do |vb1|
    vb1.memory = "4096"
    vb1.cpus = "2"
  end
end

